ASM_DIRS += \
    asm/overlays/gamestates/ovl_title \
    asm/overlays/gamestates/ovl_select \
    asm/overlays/gamestates/ovl_opening \
    asm/overlays/effects/ovl_Effect_Ss_KiraKira \
    asm/overlays/effects/ovl_Effect_Ss_Extra \
    asm/overlays/effects/ovl_Effect_Ss_Stick \
    asm/overlays/effects/ovl_Effect_Ss_Dead_Sound \
    asm/overlays/effects/ovl_Effect_Ss_Dead_Dd \
    asm/overlays/effects/ovl_Effect_Ss_Ice_Smoke \
    asm/overlays/effects/ovl_Effect_Ss_G_Ripple \
    asm/overlays/effects/ovl_Effect_Ss_G_Splash \
    asm/overlays/actors/ovl_Bg_Bom_Guard \
    asm/overlays/actors/ovl_Bg_Umajump \
    asm/overlays/actors/ovl_Item_B_Heart \
    asm/overlays/actors/ovl_Door_Ana \
    asm/overlays/actors/ovl_Bg_Spot01_Fusya \
    asm/overlays/actors/ovl_Obj_Elevator \
    asm/overlays/actors/ovl_Bg_Spot07_Taki \
    asm/overlays/actors/ovl_Bg_Spot01_Idomizu \
    asm/overlays/actors/ovl_Bg_Spot17_Funen \
    asm/overlays/actors/ovl_Bg_Spot00_Break \
    asm/overlays/actors/ovl_Bg_Spot15_Saku \
    asm/overlays/actors/ovl_Door_Gerudo \
    asm/overlays/actors/ovl_En_Scene_Change \
    asm/overlays/actors/ovl_En_River_Sound \
    asm/overlays/actors/ovl_En_Lightbox \
    asm/overlays/actors/ovl_Bg_Gjyo_Bridge \
    asm/overlays/actors/ovl_Bg_Spot09_Obj \
    asm/overlays/actors/ovl_Bg_Haka_MeganeBG \
    asm/overlays/actors/ovl_Bg_Ingate \
    asm/overlays/actors/ovl_Shot_Sun \
