SRC_DIRS += \
    src/overlays/actors/ovl_En_Vase \
    src/overlays/actors/ovl_En_M_Fire1 \
    src/overlays/actors/ovl_Obj_Blockstop \
    src/overlays/actors/ovl_En_Arow_Trap \
    src/overlays/actors/ovl_Door_Toki \
    src/overlays/actors/ovl_Bg_Gnd_Nisekabe \
    src/overlays/actors/ovl_Bg_Umajump \
    src/overlays/actors/ovl_En_Boom \
    src/overlays/actors/ovl_En_It \
    src/overlays/actors/ovl_En_Eg \
    src/overlays/actors/ovl_Obj_Roomtimer \
    src/overlays/actors/ovl_Bg_Spot18_Futa \
    src/overlays/actors/ovl_Item_Inbox \
    src/overlays/actors/ovl_En_Torch \
    src/overlays/actors/ovl_En_OE2 \
    src/overlays/actors/ovl_En_Nutsball \
    src/overlays/actors/ovl_En_Bird \
    src/overlays/actors/ovl_Bg_Spot00_Break \
